language: C

matrix:
  include:
    # Linux with sudo is hosted on Google Clouds
    - os: linux
      dist: trusty
      sudo: required
    # Linux with sudo is hosted on AWS
    - os: linux
      dist: trusty
    # OSX is very slow
    - os: osx

script:
  - python --version
  - ifconfig
  - pip install -r requirements.txt
  - echo "$CRED" > mycred.txt
  - bin/gd-ls
  - bin/gd-get-pub "$ACCESSCODE" -o /tmp/test.tgz && tar zxf /tmp/test.tgz -C /tmp --strip-components 1
  - rm -rf /tmp/test.tgz /tmp/MATLAB_R*
  - bin/gd-get -i "$ACCESSCODE" -o /tmp/test.tgz && tar zxf /tmp/test.tgz -C /tmp --strip-components 1
  - rm -rf /tmp/test.tgz /tmp/MATLAB_R*
  - '[[ "$TRAVIS_OS_NAME" != "linux" ]] || bin/gd-get -i "$ACCESSCODE" | tar zxf - -C /tmp --strip-components 1'
