language: C

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx

script:
  - pip install -r requirements.txt
  - echo "$CRED" > mycred.txt
  - bin/gd-ls
  - bin/gd-get-pub "$ACCESSCODE" -o /tmp/test.tgz && tar zxf /tmp/test.tgz -C /tmp --strip-components 1
  - rm -rf /tmp/test.tgz /tmp/MATLAB_R*
  - bin/gd-get -i "$ACCESSCODE" -o /tmp/test.tgz && tar zxf /tmp/test.tgz -C /tmp --strip-components 1
  - rm -rf /tmp/test.tgz /tmp/MATLAB_R*
  - bin/gd-get -i "$ACCESSCODE" | tar zxf - -C /tmp --strip-components 1
  - rm -rf /tmp/MATLAB_R*
