matrix:
  include:
    # Linux with sudo is hosted on Google Clouds
    - os: linux
      python: "2.7"
      dist: trusty
      sudo: required
      env: PYTHON=python PIP=pip GOOGLE=1
    # Linux with sudo is hosted on AWS
    - os: linux
      python: "2.7"
      dist: trusty
      env: PYTHON=python PIP=pip AWS=1
    # Linux with sudo is hosted on Google Clouds
    # Linux with sudo is hosted on AWS
    - os: linux
      language: python
      python: "3.5"
      dist: trusty
      env: PYTHON=python3 PIP=pip AWS=1

script:
  - $PYTHON --version
  - ifconfig
  - sudo $PIP install --ignore-installed -r requirements.txt
  - echo "$CRED" > mycred.txt
  - $PYTHON gd_list.py
  - echo "Testing gd-get" &&
    $PYTHON gd_get.py -i "$ACCESSCODE" -o /tmp/test.tgz &&
    rm -rf /tmp/test.tgz
  - echo "Testing gd-get-pub" &&
    $PYTHON gd_get_pub.py -i "$ACCESSCODE" -o /tmp/test.tgz &&
    rm -rf /tmp/test.tgz
  - $PYTHON gd_get.py -i "$ACCESSCODE" | echo > /dev/null
