image: python:3.5.1

pipelines:
  default:
    - step:
        script: # Mirror the master branch onto Github
          - git remote add github https://$GIT_USER:$GIT_TOKEN@github.com/hpdata/gdutil
          - git push github master
